# coding: utf-8

"""
    BlockContent Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from blockcontent.models.bar_chart import BarChart

class TestBarChart(unittest.TestCase):
    """BarChart unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BarChart:
        """Test BarChart
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BarChart`
        """
        model = BarChart()
        if include_optional:
            return BarChart(
                data = {
                    'key' : None
                    }
            )
        else:
            return BarChart(
        )
        """

    def testBarChart(self):
        """Test BarChart"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
