openapi: 3.1.1
info:
  title: BlockContent Spec
  version: 0.1.0

components:
  schemas:
    Block:
      type: object
      description: A content block, used to represent structured sections such as text, charts, etc.
      properties:
        type:
          type: string
          description: type of block
          enum:
            - chart
            - table
            - text
        chart_content:
          $ref: "#/components/schemas/ChartContent"
        table_content:
          $ref: "#/components/schemas/TableContent"
        text_content:
          $ref: "#/components/schemas/TextContent"
      required:
        - type
    ChartContent:
      type: object
      properties:
        chart_type:
          type: string
          description: type of chart
          enum:
            - bar
            - line
            - pie
            - scatter
        labels:
          type: array
          items:
            type: string
        datasets:
          type: array
          items:
            type: object
            properties:
              label:
                type: string
              data:
                type: array
                items:
                  type: number
      required:
        - chart_type
        - labels
        - datasets
    TableContent:
      type: object
      properties:
        headers:
          type: array
          items:
            type: string
        rows:
          type: array
          items:
            type: array
            items:
              type: string
      required:
        - headers
        - rows
    TextContent:
      type: object
      properties:
        text:
          type: string
      required:
        - text
