/* tslint:disable */
/* eslint-disable */
/**
 * BlockContent Spec
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BarChart
 */
export interface BarChart {
    /**
     * Generic data payload for charts
     * @type {{ [key: string]: object; }}
     * @memberof BarChart
     */
    data?: { [key: string]: object; };
}

/**
 * Check if a given object implements the BarChart interface.
 */
export function instanceOfBarChart(value: object): value is BarChart {
    return true;
}

export function BarChartFromJSON(json: any): BarChart {
    return BarChartFromJSONTyped(json, false);
}

export function BarChartFromJSONTyped(json: any, ignoreDiscriminator: boolean): BarChart {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function BarChartToJSON(json: any): BarChart {
    return BarChartToJSONTyped(json, false);
}

export function BarChartToJSONTyped(value?: BarChart | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
    };
}

