/* tslint:disable */
/* eslint-disable */
/**
 * BlockContent Spec
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChartContentDatasetsInner
 */
export interface ChartContentDatasetsInner {
    /**
     * 
     * @type {string}
     * @memberof ChartContentDatasetsInner
     */
    label?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof ChartContentDatasetsInner
     */
    data?: Array<number>;
}

/**
 * Check if a given object implements the ChartContentDatasetsInner interface.
 */
export function instanceOfChartContentDatasetsInner(value: object): value is ChartContentDatasetsInner {
    return true;
}

export function ChartContentDatasetsInnerFromJSON(json: any): ChartContentDatasetsInner {
    return ChartContentDatasetsInnerFromJSONTyped(json, false);
}

export function ChartContentDatasetsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChartContentDatasetsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'] == null ? undefined : json['label'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function ChartContentDatasetsInnerToJSON(json: any): ChartContentDatasetsInner {
    return ChartContentDatasetsInnerToJSONTyped(json, false);
}

export function ChartContentDatasetsInnerToJSONTyped(value?: ChartContentDatasetsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'label': value['label'],
        'data': value['data'],
    };
}

