/* tslint:disable */
/* eslint-disable */
/**
 * BlockContent Spec
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChartBlockDatasetsInner
 */
export interface ChartBlockDatasetsInner {
    /**
     * 
     * @type {string}
     * @memberof ChartBlockDatasetsInner
     */
    label?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof ChartBlockDatasetsInner
     */
    data?: Array<number>;
}

/**
 * Check if a given object implements the ChartBlockDatasetsInner interface.
 */
export function instanceOfChartBlockDatasetsInner(value: object): value is ChartBlockDatasetsInner {
    return true;
}

export function ChartBlockDatasetsInnerFromJSON(json: any): ChartBlockDatasetsInner {
    return ChartBlockDatasetsInnerFromJSONTyped(json, false);
}

export function ChartBlockDatasetsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChartBlockDatasetsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'] == null ? undefined : json['label'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function ChartBlockDatasetsInnerToJSON(json: any): ChartBlockDatasetsInner {
    return ChartBlockDatasetsInnerToJSONTyped(json, false);
}

export function ChartBlockDatasetsInnerToJSONTyped(value?: ChartBlockDatasetsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'label': value['label'],
        'data': value['data'],
    };
}

