/* tslint:disable */
/* eslint-disable */
/**
 * BlockContent Spec
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TableBlock
 */
export interface TableBlock {
    /**
     * 
     * @type {Array<string>}
     * @memberof TableBlock
     */
    headers?: Array<string>;
    /**
     * 
     * @type {Array<Array<string>>}
     * @memberof TableBlock
     */
    rows?: Array<Array<string>>;
}

/**
 * Check if a given object implements the TableBlock interface.
 */
export function instanceOfTableBlock(value: object): value is TableBlock {
    return true;
}

export function TableBlockFromJSON(json: any): TableBlock {
    return TableBlockFromJSONTyped(json, false);
}

export function TableBlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): TableBlock {
    if (json == null) {
        return json;
    }
    return {
        
        'headers': json['headers'] == null ? undefined : json['headers'],
        'rows': json['rows'] == null ? undefined : json['rows'],
    };
}

export function TableBlockToJSON(json: any): TableBlock {
    return TableBlockToJSONTyped(json, false);
}

export function TableBlockToJSONTyped(value?: TableBlock | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'headers': value['headers'],
        'rows': value['rows'],
    };
}

