/* tslint:disable */
/* eslint-disable */
/**
 * BlockContent Spec
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TableContent
 */
export interface TableContent {
    /**
     * 
     * @type {Array<string>}
     * @memberof TableContent
     */
    headers: Array<string>;
    /**
     * 
     * @type {Array<Array<string>>}
     * @memberof TableContent
     */
    rows: Array<Array<string>>;
}

/**
 * Check if a given object implements the TableContent interface.
 */
export function instanceOfTableContent(value: object): value is TableContent {
    if (!('headers' in value) || value['headers'] === undefined) return false;
    if (!('rows' in value) || value['rows'] === undefined) return false;
    return true;
}

export function TableContentFromJSON(json: any): TableContent {
    return TableContentFromJSONTyped(json, false);
}

export function TableContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): TableContent {
    if (json == null) {
        return json;
    }
    return {
        
        'headers': json['headers'],
        'rows': json['rows'],
    };
}

export function TableContentToJSON(json: any): TableContent {
    return TableContentToJSONTyped(json, false);
}

export function TableContentToJSONTyped(value?: TableContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'headers': value['headers'],
        'rows': value['rows'],
    };
}

