/* tslint:disable */
/* eslint-disable */
/**
 * BlockContent Spec
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TextBlock
 */
export interface TextBlock {
    /**
     * 
     * @type {string}
     * @memberof TextBlock
     */
    content?: string;
}

/**
 * Check if a given object implements the TextBlock interface.
 */
export function instanceOfTextBlock(value: object): value is TextBlock {
    return true;
}

export function TextBlockFromJSON(json: any): TextBlock {
    return TextBlockFromJSONTyped(json, false);
}

export function TextBlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): TextBlock {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : json['content'],
    };
}

export function TextBlockToJSON(json: any): TextBlock {
    return TextBlockToJSONTyped(json, false);
}

export function TextBlockToJSONTyped(value?: TextBlock | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
    };
}

