/* tslint:disable */
/* eslint-disable */
/**
 * BlockContent Spec
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TextContent
 */
export interface TextContent {
    /**
     * 
     * @type {string}
     * @memberof TextContent
     */
    text: string;
}

/**
 * Check if a given object implements the TextContent interface.
 */
export function instanceOfTextContent(value: object): value is TextContent {
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function TextContentFromJSON(json: any): TextContent {
    return TextContentFromJSONTyped(json, false);
}

export function TextContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): TextContent {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
    };
}

export function TextContentToJSON(json: any): TextContent {
    return TextContentToJSONTyped(json, false);
}

export function TextContentToJSONTyped(value?: TextContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
    };
}

