/*
 * BlockContent Spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TableContent {
    #[serde(rename = "headers")]
    pub headers: Vec<String>,
    #[serde(rename = "rows")]
    pub rows: Vec<Vec<String>>,
}

impl TableContent {
    pub fn new(headers: Vec<String>, rows: Vec<Vec<String>>) -> TableContent {
        TableContent {
            headers,
            rows,
        }
    }
}

